name: Quality

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  quality:
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4', '8.0', '8.1', '8.2', 'latest' ]
    runs-on: ${{ matrix.operating-system }}
    name: PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2 # https://github.com/shivammathur/setup-php
        with:
          php-version: ${{ matrix.php-versions }}
          # Shared extensions can be disabled by prefixing them with a :.
          # All extensions depending on the specified extension will also be disabled.
          extensions: zip, :opcache
          coverage: xdebug
      - uses: actions/checkout@v3
      - name: Validate composer.json
        run: composer validate --strict
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Security audit
        run: composer audit
      - name: PHPUnit
        run: php vendor/bin/phpunit
